### ISSUE TITLE
input fields for arguments and variable search

### ISSUE THREAD

**Issue by bullsei** [varren/ViragDevTool#3]
Hi, 
i noticed that the input fields for global variable search and arguments are not always clickable, so inputting something is not possible. it seems like that it has something todo that long lists shown in the frames above(and behind) the input boxes are causing this issue.

**Comment by varren** [comment]
i made a fix in version 0.19, hope it works fine now.

**Comment by bullsei** [comment]
Thanks for the fix, It works fine now. I noticed another thing: after a reload there are 5 search results in the left side. After i click on one result a lot more results appear. Is this behavior intended? I made a clip of this: https://1drv.ms/v/s!AjVne4_AjdPXiMdwmpPInvd7du-FpQ

**Comment by varren** [comment]
Hey sry for the delay and thx for reporting. [Should be fixed in v0.20+](https://github.com/varren/ViragDevTool/commit/6516958b868d5d1b1d1fb4465e173b4b72801004)
